module.exports = {
    "plugins": [
        "stylelint-scss"
    ],
    "rules": {
        "indentation": 4,
        "color-hex-case": "lower",
        "color-named": "never",
        "font-family-no-duplicate-names": true,
        "font-weight-notation": "named-where-possible",
        "function-calc-no-unspaced-operator": true,
        "function-comma-space-after": "always-single-line",
        "function-comma-space-before": "never",
        "function-max-empty-lines": 1,
        "function-name-case": "lower",
        "function-url-no-scheme-relative": true,
        "number-leading-zero": "never",
        "number-no-trailing-zeros": true,
        "string-no-newline": true,
        "string-quotes": "double",
        "length-zero-no-unit": true,
        "unit-whitelist": ["px", "rem", "deg", "vh", "vw", "%", "s", "ms"],
        "unit-case": "lower",
        "value-keyword-case": "lower",
        "value-no-vendor-prefix": true,
        "shorthand-property-no-redundant-values": true,
        "property-case": "lower",
        "property-no-unknown": true,
        "property-no-vendor-prefix": true,
        "declaration-bang-space-after": "never",
        "declaration-bang-space-before": "always",
        "declaration-empty-line-before": "never",
        "declaration-colon-newline-after": "always-multi-line",
        "declaration-block-no-duplicate-properties": true,
        "declaration-block-semicolon-newline-after": "always",
        "declaration-block-single-line-max-declarations": 1,
        "declaration-block-trailing-semicolon": "always",
        "block-closing-brace-empty-line-before": "never",
        "block-closing-brace-newline-after": "always",
        "block-closing-brace-newline-before": "always",
        "block-no-empty": true,
        "block-opening-brace-newline-after": "always",
        "block-opening-brace-space-before": "always",
        "selector-attribute-quotes": "never",
        "selector-class-pattern": "^[a-z0-9_-]+$",
        "selector-combinator-space-after": "always",
        "selector-combinator-space-before": "always",
        "selector-descendant-combinator-no-non-space": true,
        "selector-max-compound-selectors": 3,
        "selector-max-specificity": "2,2,2",
        "selector-max-attribute": 0,
        "selector-no-qualifying-type": true,
        "selector-max-type": 0,
        "selector-max-universal": 0,
        "selector-no-vendor-prefix": true,
        "selector-pseudo-class-case": "lower",
        "selector-pseudo-class-no-unknown": [true, {"ignorePseudoClasses": ["global", "local"]}],
        "selector-pseudo-class-parentheses-space-inside": "never",
        "selector-pseudo-element-case": "lower",
        "selector-pseudo-element-colon-notation": "single",
        "selector-pseudo-element-no-unknown": [true, {"ignorePseudoElements": ["global", "local"]}],
        "selector-type-case": "lower",
        "selector-type-no-unknown": true,
        "selector-max-empty-lines": 0,
        "selector-list-comma-space-after": "always",
        "selector-list-comma-space-before": "never",
        "rule-empty-line-before": ["always", {"ignore": ["after-comment", "inside-block"]}],
        "max-empty-lines": 1,
        "max-line-length": 150,
        "max-nesting-depth": 2,
        "no-empty-source": true,
        "no-eol-whitespace": true,
        "no-extra-semicolons": true,
        "no-invalid-double-slash-comments": true
    }
}